### ISSUE TITLE
Why use a localhost callback URL?

### ISSUE THREAD

**Issue by RoboMWM** [Ratismal/DriveBackup#4]
Albeit I'm a OneDrive fan I'm using the empty space in Google Drive for my test server, and after I click accept... it's attempting to use localhost. Thing is, this server is running on a Linux box, so I'm using my personal computer to visit the link... and since I have a firewall on there too I can't just change localhost to its IP...

**Comment by Ratismal** [comment]
Sorry you're having issues! To be honest, I have no idea. I simply use the Google Drive API, and it generates the credential for me. All of the web browser oauth2 stuff is entirely done in Google's API, and I have no control over it. 

To make generating the initial credential easier, I have created a companion program called [DriveCredentials](https://github.com/Ratismal/DriveCredentials/releases), You can run it on any computer with Java, and provided that it has a browser you can generate a credential file from there. This credential file can then be copied to any server you wish to use Google Drive with. You can also use [DriveCredentials](https://github.com/Ratismal/DriveCredentials/releases) to generate OneDrive credential files, but OneDrive doesn't even have a Java API so generating a credential is mostly based on manual input.

If you're a bit weary of using another program to generate credentials, I totally understand. Keep in mind that [DriveCredentials](https://github.com/Ratismal/DriveCredentials/releases) and DriveBackup are completely open-sourced so you can ensure that nothing suspicious is being done with your information.

Again, I'm sorry about these issues, but there's really no way for me to do anything about them as it's all done upstream. Let me know if you've managed to get things working so that I can close this thread.

**Comment by RoboMWM** [comment]
Hmm, I know BackupLikeMe allows you to paste in an auth key (albeit using DropBox). That being said, I forgot about the alternative method so I'll go ahead and use that, thanks.
