### ISSUE TITLE
[Suggestion] Restore Option

### ISSUE THREAD

**Issue by FatherWh0** [Ratismal/DriveBackup#8]
I am on a limited bandwidth at home and thus was looking for a plugin to back up to my google drive. This plugin looks like it would do very well. Unfortunately I have had a few incidences where I've had to restore a backup of a world map. Since my servers are hosted on Beastnode, Fragnet and the like I would be at the mercy of their tech support to download, unzip and copy my world folder. This could lead to down time. I've seen as slow as 3 hour response and once watched a ticket sit for 12 hours before being answered (thanks fragnet). 

The option to restore a backed up world would make this plugin perfect for me. I have found deleting the old world is required to restore a world folder. For extra multiverse worlds this is no problem but for any of the 3 vanilla worlds this could be tricky since the plugin has to run on a live server and those worlds can't be unloaded. If a restore function had options to restore a specific world from the backup and to extract the world folder to a different folder name than it was backed up from that would resolve issues with restoring a live world.

Example: A backup session stores world, world_nether, world_the_end and world_bob in a zip file on a google drive. The player chooses to restore world_nether but rather than to world_nether folder to a folder called world_nether_2. The server owner then shuts down the server, deletes world_nether, renames world_nether_2 to world_nether, then starts the server. His nether has then been restored from the backup.

Thank you for your time and I hope you'll consider this option.

**Comment by Ratismal** [comment]
This is a valid suggestion, and one that I will most likely implement in the future. However, it won't be as a restore function, but will most likely just download backups into a downloads folder. I have to stress that this is a lot of work to implement, because I have to implement it for three different services that each use very different APIs. It may take some time before it's released.

In the meantime, let me suggest some alternatives to you. I'm assuming that on your servers, you have access to a command line. You can use this to download files directly from your google drive to your computer using the `wget` command. A brief google search turned up [this stackexchange thread](http://unix.stackexchange.com/questions/136371/how-to-download-a-folder-from-google-drive-using-terminal) which may be of use to you. More specifically, the answer that has this command in it:

```
$ wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=FILEID' -O FILENAME
```

I have tested this command with downloading one of my backups, and it worked perfectly. I hope this works for you while you wait for me to implement this feature.

**Comment by RoboMWM** [comment]
>  I'm assuming that on your servers, you have access to a command line.

No, most shared hosts do not provide SSH access to end-users.

**Comment by FatherWh0** [comment]
Indeed not. I am limited to my server console and ftp file access.
